# Generated by Django 4.2.6 on 2023-11-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.FileField(upload_to='')),
                ('MedicineName', models.CharField(max_length=50)),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
