# Generated by Django 4.2.6 on 2023-12-07 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Medicineid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.product')),
                ('Userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.user')),
            ],
        ),
    ]
