# Generated by Django 4.2.6 on 2023-12-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='entry',
            field=models.CharField(choices=[('APPROVED', 'APPROVED'), ('PENDING', 'PENDING'), ('REJECT', 'REJECT')], default='PENDING', max_length=20),
        ),
    ]
